import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/About.module.css";
import Header from "@/components/Header";

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header/>
        <img src="/Quack Attack Journey to the city.png"></img>
        <div className={styles.home}>
            <p className={styles.message}>In "Quack Attack," it's not just about collecting breadcrumbs – it's about saving the farm from certain starvation and emerging as the ultimate hero! Dive into a captivating metroidvania platform-scrolling adventure that will push you to your limits and keep you on the edge of your seat.</p>
            <p className={styles.message}>As our courageous duck protagonist, you'll navigate through a charming yet perilous world filled with enemies lurking around every corner. From pesky pests to formidable foes, you'll engage in exhilarating battles that will put your skills to the test. But fear not, for with each victory, you'll inch closer to your ultimate goal: defeating Chef Louis, the mastermind behind the farm's plight. </p>
            <p className={styles.message}>Chef Louis isn't just any adversary – he's the head chef and owner of the biggest bakery in town, and he'll stop at nothing to thwart your noble quest. With cunning strategies and formidable culinary skills, he'll challenge you in ways you never thought possible. But armed with determination and a beakful of courage, you'll face him head-on in an epic showdown for the fate of the farm.</p>
            <p className={styles.message}>But "Quack Attack" isn't just about action-packed battles – it's also about engaging dialogues that will immerse you in the rich tapestry of the game world. From quirky characters to heartfelt moments, every interaction will leave you craving more.</p>
            <p className={styles.message}>So, gear up, sharpen your skills, and get ready to quack your way to victory in "Quack Attack" – the ultimate test of bravery, skill, and determination! </p>
            </div>
      </main>
    </>
  );
}
