import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/DevTeam.module.css';
import Header from '@/components/Header';
import Creators from '@/components/Creators';
import Footer from '@/components/Footer';

const creators = [
  {
    imageUrl: '/duck.png',
    name: 'Melissa. J',
    text: 'Character Designer, Animator and Developer.',
  },
  {
    imageUrl: '/duck.png',
    name: 'Kyanna. K',
    text: 'Background Designer and Developer.',
  },
  {
    imageUrl: '/duck.png',
    name: 'Arabella. A',
    text: 'Background Designer and Dialogue Developer.',
  },
  {
    imageUrl: '/duck.png',
    name: 'Daniel. D',
    text: 'Background Designer and Developer.',
  },
];

export default function DevTeam() {
  return (
    <>
      <Head>
        <title>Meet The Team</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header />
        <img src="/Quack Attack Journey to the city.png" alt="Quack Attack Journey to the city" />
        <div className={styles.home}>
        <img className={styles.border} src="borderwhite.png" alt="border"></img>
            <div className={styles.section}>
          {creators.map((creator, index) => (
            <Creators
              key={index}
              imageUrl={creator.imageUrl}
              name={creator.name}
              text={creator.text}
              className={styles.card}
            />
          ))}
          </div>
          <img className={styles.border} src="borderwhite.png" alt="border"></img>
        </div>
        <Footer/>
      </main>
    </>
  );
}
