import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Features.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function Features() {
  return (
    <>
      <Head>
        <title>Features</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={`${styles.main}`}>
        <Header/>
        <img src="/Quack Attack Journey to the city.png"></img>
        <div className={styles.home}>
        <div className={styles.container}>
            <div className={styles.row1}>
              <div className={styles.text}>
                <h2>Discover new worlds</h2>
                <p>Go from farm to city and experience the sights 
                and sounds of the different environments. Meet
                the locals and gain experience along the way. 
                Jump on platforms, touch the sky and most 
                importantly, make it to the final battle ground, 
                the bakery.</p>
              </div>
              <div className={styles.image}>
                <img src="/scenery.png" alt="Image" />
              </div>
            </div>
            <div className={styles.row2}>
              <div className={styles.text}>
                <h2>Level Up!</h2>
                <p>Watch your duck grow from being stuck in its shell 
                to being a full grow adult! Expand your abilities
                as you defeat enemies and grow older. Purchase
                power ups in the store to help defeat bigger
                enemies that stand in your way.</p>
              </div>
              <div className={styles.image}>
                <img src="/duck evolution.png" alt="Image" />
              </div>
            </div>
            <div className={styles.row3}>
              <div className={styles.text}>
                <h2>Become the hero</h2>
                <p>Save your friends from starvation. Follow along 
                with the story and get advice from Owl, the 
                wisest bird on the farm. Reach your goal of 
                running the bakery one breadcrumb at a time and
                become the hero you know you can be!.</p>
              </div>
              <div className={styles.image}>
                <img src="/hero chef.png" alt="Image" />
              </div>
            </div>
          </div>
          </div>
          <Footer/>
    </main>
    </>
  );
}
