import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quack Attack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header/>
        <img src="/Quack Attack Journey to the city.png"></img>
        <div className={styles.home}>
          <img className={styles.border} src="borderwhite.png" alt="border"></img>
          <h1 className={styles.welcome}>Welcome to Quack Attack </h1>
          <h2 className={styles.sum}>Quick words from the team</h2>
          <p className={styles.message}>Hey there! </p>
          <p className={styles.message}>We're super excited to welcome you to the soft launch of our new game, "Quack Attack"! 🎉 </p>
          <p className={styles.message}>We hope you have a blast exploring the game and diving into all the fun it has to offer. Just a heads up, "Quack Attack" is still in its early stages of development, so we're counting on you to help us make it even better with your feedback and suggestions!</p>
          <p className={styles.message}>Thanks a bunch for being a part of this journey with us. We can't wait to see what you think of "Quack Attack" and to share many more awesome adventures together! Without further adeu, Let's get quacking! 🦆💥</p>
          <p className={styles.message}>- Quack Attack Team</p>
          <img className={styles.border2} src="borderwhite.png" alt="border"></img>
          </div>
          <Footer/>
      </main>
    </>
  );
}
