import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Video.module.css";
import Header from "@/components/Header";

export default function Video() {
  return (
    <>
      <Head>
        <title>Video</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header/>
        <img src="/Quack Attack Journey to the city.png"></img>
        <video className={styles.video} controls>
          <source src="/Promo.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <div className={styles.home}>
        <h1 className={styles.welcome}>Watch this short promo video </h1>
        </div>
      </main>
    </>
  );
}
